// Public surface of the Data Foundry (M3) — the tiered, inspectable, owned dataset layer.

export type { DocumentRecord, Tier, Origin } from "./DocumentRecord.ts";
export { DataKinds, TableForKind, KindForProvider, IsDataKind } from "./DataKinds.ts";
export type { DataKind } from "./DataKinds.ts";
export { FoundryStores } from "./FoundryStores.ts";
export type { KindStat } from "./FoundryStores.ts";
export { ClassifyDocument } from "./Tiering.ts";
export type { TierDecision } from "./Tiering.ts";
export { DetectSpdx, NormalizeLicense } from "./SpdxDetector.ts";
export type { SpdxResult } from "./SpdxDetector.ts";
export { HashingEmbedding, CosineSimilarity } from "./Embedding.ts";
export type { DocumentStore, SimilarHit, RepoSummary, FoundryStats, DocumentFilter, DocumentPage } from "./DocumentStore.ts";
export { InMemoryDocumentStore } from "./InMemoryDocumentStore.ts";
export { BuildReport, RenderReportText } from "./QualityReport.ts";
export type { FoundryReport } from "./QualityReport.ts";
export { IngestDocuments, ExportTrainingText } from "./Ingest.ts";
export type { SourceInput, IngestStats } from "./Ingest.ts";
export { CreateDashboardHandler, CreateDashboardParts, StartDashboard } from "./Dashboard.ts";
export type { DashboardHandler, DashboardOptions } from "./Dashboard.ts";
export type { LearnSettings, LearnEvent, LearnFn, TrainSettings, TrainEvent, TrainFn } from "./DashboardTypes.ts";
export { GetSystemInfo } from "./SystemInfo.ts";
export type { SystemInfo } from "./SystemInfo.ts";
export { DescribeModel } from "./ModelInfo.ts";
export type { ModelInfo, ParamGroup } from "./ModelInfo.ts";
export type { ChatStore, ConversationSummary, ChatMessage } from "./ChatStore.ts";
export { InMemoryChatStore } from "./InMemoryChatStore.ts";
export { PostgresChatStore } from "./PostgresChatStore.ts";
export { PostgresCheckpointStore } from "./PostgresCheckpointStore.ts";
export type { CheckpointSummary } from "./PostgresCheckpointStore.ts";
export { ChatService } from "./ChatService.ts";
export type { ChatStreamFn, ChatOpts } from "./ChatService.ts";
export type { IngestProgress } from "./WebSource.ts";
export { HtmlToText } from "./HtmlToText.ts";
export { IngestFromWeb } from "./WebSource.ts";
export type { WebProvider } from "./WebSource.ts";
export { CreateGitHubProvider } from "./GitHubProvider.ts";
export type { GitHubOptions, HttpJson } from "./GitHubProvider.ts";
export { CreateGitHubRepoProvider } from "./GitHubRepoProvider.ts";
export type { GitHubRepoOptions } from "./GitHubRepoProvider.ts";
export { CreateLocalRepoProvider } from "./LocalRepoProvider.ts";
export type { LocalRepoOptions } from "./LocalRepoProvider.ts";
export { CreateOasstProvider, Oasst1Url, Oasst2Url } from "./OasstProvider.ts";
export type { OasstOptions } from "./OasstProvider.ts";
export { CreateWikipediaProvider } from "./WikipediaProvider.ts";
export type { WikipediaOptions } from "./WikipediaProvider.ts";
export { CreateGsmProvider, GsmRowToDoc, GsmSplits } from "./GsmProvider.ts";
export type { GsmOptions } from "./GsmProvider.ts";
export { FetchWithBackoff, CircuitBreaker, HttpError, RetryAfterToMs, IsTransient } from "./HttpBackoff.ts";
export type { BackoffOptions } from "./HttpBackoff.ts";
export type { CollectionState, CollectionStateStore } from "./CollectionState.ts";
export { ComputeExhausted } from "./CollectionState.ts";
export { InMemoryCollectionStateStore } from "./InMemoryCollectionStateStore.ts";
export { PostgresCollectionStateStore } from "./PostgresCollectionStateStore.ts";
export { FetchRepoFiles, DefaultRepoLimits } from "./RepoArchive.ts";
export type { RepoFile, RepoLimits } from "./RepoArchive.ts";
export { AssessRepo, LevelRank, EmptyAssessment } from "./RepoQuality.ts";
export type { RepoLevel, RepoAssessment, RepoIngestInfo } from "./RepoQuality.ts";
export { DefaultGitHubJson, DefaultGitHubBytes } from "./GitHubHttp.ts";
export type { FetchBytes } from "./GitHubHttp.ts";
export { IsSubstantiveCodePath, IsSubstantiveCodeContent, LangForPath } from "./CodeFileFilter.ts";
export { CreateWebSearchProvider } from "./WebSearchProvider.ts";
export type { SearchBackend, SearchHit, PageFetch, WebSearchOptions } from "./WebSearchProvider.ts";
